"""Add Google OAuth support

Revision ID: 03632dfa9375
Revises: dcf01ea7a6c5
Create Date: 2025-12-07 17:53:37.956331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03632dfa9375'
down_revision: Union[str, None] = 'dcf01ea7a6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_requests', 'platform',
               existing_type=postgresql.ENUM('linkedin', 'instagram', 'tiktok', 'facebook', 'twitter', 'multi_format', name='platform'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'linkedin'::platform"))
    op.add_column('usage_analytics', sa.Column('platform', sa.Enum('LINKEDIN', 'INSTAGRAM', 'TIKTOK', 'FACEBOOK', 'TWITTER', 'MULTI_FORMAT', name='platform'), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'google_id')
    op.drop_column('usage_analytics', 'platform')
    op.alter_column('content_requests', 'platform',
               existing_type=sa.String(),
               type_=postgresql.ENUM('linkedin', 'instagram', 'tiktok', 'facebook', 'twitter', 'multi_format', name='platform'),
               existing_nullable=False,
               existing_server_default=sa.text("'linkedin'::platform"))
    # ### end Alembic commands ###
