"""Add email verification fields

Revision ID: 1837f7fb6221
Revises: e1a02767c419
Create Date: 2025-12-10 15:05:53.652053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1837f7fb6221'
down_revision: Union[str, None] = 'e1a02767c419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add email verification columns
    op.add_column('users', sa.Column('email_verified', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires', sa.DateTime(), nullable=True))

    # Set default values for existing users and Google OAuth users
    op.execute("UPDATE users SET email_verified = 1 WHERE google_id IS NOT NULL")
    op.execute("UPDATE users SET email_verified = 0 WHERE google_id IS NULL AND email_verified IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code_expires')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
