"""Add Google OAuth support

Revision ID: dcf01ea7a6c5
Revises: 7ffe6803ad79
Create Date: 2025-12-07 17:51:27.119502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcf01ea7a6c5'
down_revision: Union[str, None] = '7ffe6803ad79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_requests', 'platform',
               existing_type=postgresql.ENUM('linkedin', 'instagram', 'tiktok', 'facebook', 'twitter', 'multi_format', name='platform'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'linkedin'::platform"))
    op.alter_column('usage_analytics', 'platform',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LINKEDIN', 'INSTAGRAM', 'TIKTOK', 'FACEBOOK', 'TWITTER', 'MULTI_FORMAT', name='platform'),
               existing_nullable=True)
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'google_id')
    op.alter_column('usage_analytics', 'platform',
               existing_type=sa.Enum('LINKEDIN', 'INSTAGRAM', 'TIKTOK', 'FACEBOOK', 'TWITTER', 'MULTI_FORMAT', name='platform'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('content_requests', 'platform',
               existing_type=sa.String(),
               type_=postgresql.ENUM('linkedin', 'instagram', 'tiktok', 'facebook', 'twitter', 'multi_format', name='platform'),
               existing_nullable=False,
               existing_server_default=sa.text("'linkedin'::platform"))
    # ### end Alembic commands ###
