"""Add current_plan and plan_started_at to User model

Revision ID: e1a02767c419
Revises: 03632dfa9375
Create Date: 2025-12-10 14:47:39.717386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a02767c419'
down_revision: Union[str, None] = 'dcf01ea7a6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_requests', 'platform',
               existing_type=postgresql.ENUM('linkedin', 'instagram', 'tiktok', 'facebook', 'twitter', 'multi_format', name='platform'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'linkedin'::platform"))
    op.add_column('usage_analytics', sa.Column('platform', sa.Enum('LINKEDIN', 'INSTAGRAM', 'TIKTOK', 'FACEBOOK', 'TWITTER', 'MULTI_FORMAT', name='platform'), nullable=True))
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)

    # Add current_plan and plan_started_at columns to users table
    op.add_column('users', sa.Column('current_plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan_started_at', sa.DateTime(), nullable=True))

    # Set default values for existing users
    op.execute("UPDATE users SET current_plan = 'free' WHERE current_plan IS NULL")
    op.execute("UPDATE users SET plan_started_at = created_at WHERE plan_started_at IS NULL")

    # Make password_hash nullable for Google OAuth
    op.alter_column('users', 'password_hash', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert password_hash to not nullable
    op.alter_column('users', 'password_hash', nullable=False)

    # Drop current_plan and plan_started_at columns
    op.drop_column('users', 'plan_started_at')
    op.drop_column('users', 'current_plan')

    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.drop_column('usage_analytics', 'platform')
    op.alter_column('content_requests', 'platform',
               existing_type=sa.String(),
               type_=postgresql.ENUM('linkedin', 'instagram', 'tiktok', 'facebook', 'twitter', 'multi_format', name='platform'),
               existing_nullable=False,
               existing_server_default=sa.text("'linkedin'::platform"))
    # ### end Alembic commands ###
